# THIS DOES NOT WORK
# IT WILL BE THE NEXT STEP FOR CONFIGURING JENKINS MASTER WITH XML FILES

# Configuring Jenkins Nodes:
# Need to Configure Jenkins Controller with 'jenkins' user,
# and create an SSH Key for that user.
# Then copy that SSH Key to all the hosts.

# To add the Node to the Jenkins controller, manually I added things in the GUI.
# The only things required on the Node is:
  # 1. Add 'jenkins' user
  # 2. Copy public key for the ssh key created on jenkins controller.
  #   a. Might require updating sshd_config, will test it
  # 3. Add the Node as a 'known host' to jenkins controller
  # 4. All of the above should be all that's needed on the Node to create it as an agent
  #     The jenkins agent is downloaded to the node when configured via Jenkins Controller.
  # 5. Last step, add all the necessary software to be used.

# After doing the steps above, you can configure the jenkins-controller to add the new Node:
#   Research doing this via APIs or an existing jenkins playbook.
#   If the existing Jenkins playbooks don't have it, I CAN ADD THE FEATURE!!!!!!!

---
- name: Configure the Jenkins Master Server
- hosts: jenkins_master
  vars_files:
    - ~/ansible/vars/bootstrap_vars
    - ~/ansible/vault
  tasks:
  - name: Configure Jenkins
    copy:
      src: /root/ansible/config_files/jenkins_master_config.xml
      dest: /var/lib/jenkins/config.xml
      owner: jenkins
      group: jenkins
      mode: 0644
    notify: Restart Jenkins

  - name: Configure Jenkins Plugins
    copy:
      src: /root/ansible/config_files/jenkins_plugins.txt
      dest: /tmp/jenkins_plugins.txt
      owner: jenkins
      group: jenkins
      mode: 0644
    notify: Restart Jenkins

  - name: Install Jenkins Plugins
    command: "xargs /usr/bin/jenkins-plugin-cli -f < /tmp/jenkins_plugins.txt"
    args:
      creates: /var/lib/jenkins/jenkins-cli.jar
    notify: Restart Jenkins

  - name: Configure Jenkins Security
    copy:
      src: /root/ansible/config_files/jenkins_security.groovy
      dest: /var/lib/jenkins/init.groovy.d/security.groovy
      owner: jenkins
      group: jenkins
      mode: 0644
    notify: Restart Jenkins

  - name: Configure Jenkins Jobs
    copy:
      src: /root/ansible/config_files/jenkins_jobs.xml
      dest: /var/lib/jenkins/jobs/jenkins_jobs/config.xml
      owner: jenkins
      group: jenkins
      mode: 0644
    notify: Restart Jenkins

  - name: Restart Jenkins
    service:
      name: jenkins
      state: restarted
