---
- name: Update all hosts
  hosts: all
  tasks:
  - name: Update RHEL hosts
    dnf:
      name: "*"
      state: present
    when: ansible_facts['os_family'] == 'RedHat'

  - name: Add packages to Debian bastion hosts
    apt:
      name: "*"
      state: present
    when: ansible_facts['os_family'] == 'Debian'